name: My first Github action
on: [push]
jobs: 
  build-app:  
    runs-on:  ubuntu-latest
    steps:
      - uses:  actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.13.1"
      - name: check
        run:  node -v
      - name: install node-modules
        run:  npm i
      - name: build project
        run: npm run build
    